import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert several XML RSS (version 2.0) feeds from a list of URLs
 * given in an XML input file into the corresponding HTML output files, plus an
 * HTML index page with links to the individual feed pages.
 *
 * @author Zacharia Agourrame
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     * <!DOCTYPE html>
     * <html lang="en">
     * <head>
     *  <title>the channel tag title as the page title</title>
     * </head>
     * <body>
     *  <h1>the page title inside a link to the <channel> link</h1>
     *  <p>
     *  the channel description
     *  </p>
     *  <table border="1">
     *   <tr>
     *    <th>Date</th>
     *    <th>Source</th>
     *    <th>News</th>
     *   </tr>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // find indices of required channel children
        int titleIndex = getChildElement(channel, "title");
        int linkIndex = getChildElement(channel, "link");
        int descIndex = getChildElement(channel, "description");

        // default values in case tags are missing or empty
        String title = "Empty Title";
        String link = "";
        String description = "No description";

        if (titleIndex != -1 && channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }

        if (linkIndex != -1 && channel.child(linkIndex).numberOfChildren() > 0) {
            link = channel.child(linkIndex).child(0).label();
        }

        if (descIndex != -1 && channel.child(descIndex).numberOfChildren() > 0) {
            description = channel.child(descIndex).child(0).label();
        }

        // write HTML header, title, and table header row
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>");
        out.println("<a href=\"" + link + "\">" + title + "</a>");
        out.println("</h1>");
        out.println("<p>");
        out.println(description);
        out.println("</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     *  </table>
     * </body>
     * </html>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first tag child of the {@code XMLTree} matching the
     *  given tag or -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int elnum = -1;
        boolean found = false;
        // search children for matching tag
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (!found && xml.child(i).isTag() && xml.child(i).label().equals(tag)) {
                elnum = i;
                found = true;
            }
        }

        return elnum;

    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // find indices of item fields
        int dateIndex = getChildElement(item, "pubDate");
        int sourceIndex = getChildElement(item, "source");
        int newsIndex = getChildElement(item, "title");
        int descIndex = getChildElement(item, "description");
        int linkIndex = getChildElement(item, "link");

        // default values if fields are missing
        String date = "No date available";
        String source = "No source available";
        String news = "No title available";
        String link = "";

        if (dateIndex != -1 && item.child(dateIndex).numberOfChildren() > 0) {
            date = item.child(dateIndex).child(0).label();
        }

        // build source link if source tag exists
        if (sourceIndex != -1) {
            String sourceText = "";

            if (item.child(sourceIndex).numberOfChildren() > 0) {
                sourceText = item.child(sourceIndex).child(0).label();
            }

            source = "<a href=\"" + item.child(sourceIndex).attributeValue("url") + "\">"
                    + sourceText + "</a>";
        }

        // use title, or fall back to description
        if (newsIndex != -1 && item.child(newsIndex).numberOfChildren() > 0) {
            news = item.child(newsIndex).child(0).label();
        } else if (descIndex != -1 && item.child(descIndex).numberOfChildren() > 0) {
            news = item.child(descIndex).child(0).label();
        }

        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            link = item.child(linkIndex).child(0).label();
        }

        // write table row with date, source, and linked news title
        out.println("<tr>");

        out.println("<td>" + date + "</td>");
        out.println("<td>" + source + "</td>");

        out.println("<td>");
        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            out.println("<a href=\"" + link + "\">" + news + "</a>");
        } else {
            out.println(news);
        }
        out.println("</td>");

        out.println("</tr>");
    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        assert url != null : "Violation of: url is not null";
        assert file != null : "Violation of: file is not null";
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        XMLTree rssTree = new XMLTree1(url);

        // validate RSS 2.0 structure before processing
        if (rssTree.label().equals("rss") && rssTree.hasAttribute("version")
                && rssTree.attributeValue("version").equals("2.0")
                && rssTree.numberOfChildren() > 0 && rssTree.child(0).isTag()
                && rssTree.child(0).label().equals("channel")) {

            SimpleWriter fileOut = new SimpleWriter1L(file);

            XMLTree channel = rssTree.child(0);

            outputHeader(channel, fileOut);

            // process each item in the channel
            for (int i = 0; i < channel.numberOfChildren(); i++) {
                if (channel.child(i).isTag() && channel.child(i).label().equals("item")) {
                    processItem(channel.child(i), fileOut);
                }
            }

            outputFooter(fileOut);

            fileOut.close();
        } else {
            out.println("Error: " + url + " is not a valid RSS 2.0 feed");
        }
    }

    /**
     * Outputs an HTML index page with a title (from the {@code feeds} tag's
     * title attribute) and an unordered list of links to the individual feed
     * pages, one per {@code feed} tag in {@code feeds}.
     *
     * @param feeds
     *            the {@code XMLTree} with the <feeds> root containing one or
     *            more <feed> tags, each with url, name, and file attributes
     * @param file
     *            the name of the HTML index output file
     * @updates out.content
     * @requires [the root of feeds is a <feeds> tag with a title attribute]
     * @ensures <pre>
     * [an HTML index page with the feeds title, a heading, and an unordered
     *   list of links (name to url) is saved to file]
     * </pre>
     */
    private static void outputIndex(XMLTree feeds, String file) {
        assert feeds != null : "Violation of: feeds is not null";
        assert file != null : "Violation of: file is not null";
        assert feeds.isTag() && feeds.label().equals("feeds")
                : "Violation of: the label root of feeds is a <feeds> tag";
        assert feeds.hasAttribute("title") : "Violation of: feeds has a title attribute";

        SimpleWriter out = new SimpleWriter1L(file);

        String title = feeds.attributeValue("title");

        // write index page header
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>" + title + "</h1>");
        out.println("<ul>");

        // add a list item linking to each feed's output file
        for (int i = 0; i < feeds.numberOfChildren(); i++) {
            XMLTree feed = feeds.child(i);
            if (feed.isTag() && feed.label().equals("feed")) {
                out.println("<li><a href=\"" + feed.attributeValue("file") + "\">"
                        + feed.attributeValue("name") + "</a></li>");
            }
        }

        out.println("</ul>");
        out.println("</body>");
        out.println("</html>");

        out.close();
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        // get input XML file and index output file from user
        out.print("Enter the name of an XML file with a list of RSS feed URLs: ");
        String inputFile = in.nextLine();

        XMLTree feeds = new XMLTree1(inputFile);

        out.print("Enter the name of an HTML file for the index output: ");
        String indexFile = in.nextLine();

        outputIndex(feeds, indexFile);

        // process each feed and generate its HTML page
        for (int i = 0; i < feeds.numberOfChildren(); i++) {
            XMLTree feed = feeds.child(i);
            if (feed.isTag() && feed.label().equals("feed")) {
                String url = feed.attributeValue("url");
                String file = feed.attributeValue("file");
                processFeed(url, file, out);
            }
        }

        in.close();
        out.close();
    }

}
