import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Zacharia Agourrame
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     * <!DOCTYPE html>
     * <html lang="en">
     * <head>
     *  <title>the channel tag title as the page title</title>
     * </head>
     * <body>
     *  <h1>the page title inside a link to the <channel> link</h1>
     *  <p>
     *  the channel description
     *  </p>
     *  <table border="1">
     *   <tr>
     *    <th>Date</th>
     *    <th>Source</th>
     *    <th>News</th>
     *   </tr>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int titleIndex = getChildElement(channel, "title");
        int linkIndex = getChildElement(channel, "link");
        int descIndex = getChildElement(channel, "description");

        String title = "Empty Title";
        String link = channel.child(linkIndex).child(0).label();
        String description = "No description";

        if (channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }

        if (channel.child(descIndex).numberOfChildren() > 0) {
            description = channel.child(descIndex).child(0).label();
        }

        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>");
        out.println("<a href=\"" + link + "\">" + title + "</a>");
        out.println("</h1>");
        out.println("<p>");
        out.println(description);
        out.println("</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     *  </table>
     * </body>
     * </html>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first tag child of the {@code XMLTree} matching the
     *  given tag or -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int elnum = -1;

        for (int i = xml.numberOfChildren() - 1; i >= 0; i--) {
            if (xml.child(i).label().equals(tag)) {
                elnum = i;
            }
        }

        return elnum;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int dateIndex = getChildElement(item, "pubDate");
        int sourceIndex = getChildElement(item, "source");
        int newsIndex = getChildElement(item, "title");
        int descIndex = getChildElement(item, "description");
        int linkIndex = getChildElement(item, "link");

        String date = "No date available";
        String source = "No source available";
        String news = "No title available";
        String link = "";

        if (dateIndex != -1 && item.child(dateIndex).numberOfChildren() > 0) {
            date = item.child(dateIndex).child(0).label();
        }

        if (sourceIndex != -1) {
            String sourceText = "";

            if (item.child(sourceIndex).numberOfChildren() > 0) {
                sourceText = item.child(sourceIndex).child(0).label();
            }

            source = "<a href=\"" + item.child(sourceIndex).attributeValue("url") + "\">"
                    + sourceText + "</a>";
        }

        if (newsIndex != -1 && item.child(newsIndex).numberOfChildren() > 0) {
            news = item.child(newsIndex).child(0).label();
        } else if (descIndex != -1 && item.child(descIndex).numberOfChildren() > 0) {
            news = item.child(descIndex).child(0).label();
        }

        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            link = item.child(linkIndex).child(0).label();
        }

        out.println("<tr>");

        out.println("<td>" + date + "</td>");
        out.println("<td>" + source + "</td>");

        out.println("<td>");
        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            out.println("<a href=\"" + link + "\">" + news + "</a>");
        } else {
            out.println(news);
        }
        out.println("</td>");

        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter the URL of an RSS feed: ");
        String url = in.nextLine();

        XMLTree rssTree = new XMLTree1(url);

        while (!(rssTree.label().equals("rss") && rssTree.hasAttribute("version")
                && rssTree.attributeValue("version").equals("2.0"))) {

            out.println("Invalid RSS Feed");
            out.print("Enter the URL of an RSS feed: ");
            url = in.nextLine();
            rssTree = new XMLTree1(url);
        }

        out.print("Enter the name of an HTML file for output: ");
        String fileName = in.nextLine();

        SimpleWriter fileOut = new SimpleWriter1L(fileName);

        XMLTree channel = rssTree.child(0);

        outputHeader(channel, fileOut);

        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).label().equals("item")) {
                processItem(channel.child(i), fileOut);
            }
        }

        outputFooter(fileOut);

        fileOut.close();
        in.close();
        out.close();
    }

}
